<?php 
$cabinetModel = $block->getCabinetModel();
//print_r($cabinetModel);
?>


<div class="field name">
    <label class="label" for="name"><span>Safety Item Type</span></label>
    <div class="control">
        <select name="types" id="types" onchange="showDiv(this)">
            <option value="">Select One</option>
            <option value="1">Cabinet</option>
            <option value="2" >Fire Exitinguisher</option>
            <option value="3" >AED</option>
            <option value="4">Eyewash Stations</option>
            <option value="5">Spill Control</option>
        </select>
    </div>
</div>

<div name="cabinet_no" id="cabinet_no" style="display: none;">
    <div class="field name">
        <label class="label" for="name"><span>Cabinet Model Number</span></label>
        <div class="control">
            <select name="model_number" id="types" onchange="showDiv(this)">
                <?php foreach($cabinetModel as $model): ?>
                <option value="<?= $model['model_number'] ?>"><?= $model['model_number'] ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>

    <div class="field subject ">
        <label class="label" for="subject"><span>Cabinet Serial no</span></label>
        <div class="control">
            <input name="serial_number" id="serial_number" title="" value="" class="input-text" type="text" />
        </div>
    </div>

    <div class="field subject ">
        <label class="label" for="subject"><span>Cabinet Nickname</span></label>
        <div class="control">
            <input name="nickname" id="serial_number" title="" value="" class="input-text" type="text" />
        </div>
    </div>


    <div class="field telephone">
        <label class="label" for="telephone"><span>Cabinet Expiration Date</span></label>
        <div class="control">
            <input name="expiration_date" id="expiration_date" title="Cabinet Expiration Date" value=""  class="input-text" type="date" />
        </div>
    </div>
    <div class="field telephone">
        <input name="refill_reminder_status" id="cabinet_refill_reminder_status" title="Remind me to refill cabinet " value=" 1"  class="input-text" type="checkbox" /> <label class="label inline-one" for="telephone"><span>Remind me to refill cabinet</span></label>
    </div>
    <div class="field telephone">
        <input name="physical_inventory_status" id="cabinet_physical_inventory_status" title="Do Physical inventory of cabinet " value="1"  class="input-text" type="checkbox" /> <label class="label inline-one" for="telephone"><span>Do Physical inventory of cabinet</span></label>
    </div>  
</div>

<!--for Fire Extinguisher -->
<div name="fire_extinguisher" id="fire_extinguisher" style="display:none;">
    <div class="field name required">
        <label class="label" for="name"><span><?= $block->escapeHtml(__('Fire Extinguisher model/serial no')) ?></span></label>
        <div class="control">
            <input name="fire_model_number" id="fire_model_number" title="<?= $block->escapeHtmlAttr(__('Fire Extinguisher model/serial no')) ?>" value="" class="input-text" type="text"/>
        </div>
    </div>

    <div class="field subject ">
        <label class="label" for="subject"><span><?php /* @escapeNotVerified */ echo __('Fire Extinguisher Nickname') ?></span></label>
        <div class="control">
            <input name="fire_nickname" id="fire_nickname" title="<?php /* @escapeNotVerified */ echo __('Fire Extinguisher Nickname') ?>" value="" class="input-text" type="text" />
        </div>
    </div>

    <div class="field email ">
        <label class="label" for="email"><span><?= $block->escapeHtml(__('FX Expiration Date')) ?></span></label>
        <div class="control">
            <input name="fx_expiration_date" id="fx_expiration_date" title="<?= $block->escapeHtmlAttr(__('FX Expiration Date')) ?>" value="" class="input-text" type="date" />
        </div>
    </div>

    <div class="field telephone">
        <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Fire Extinguisher Service Due Date')) ?></span></label>
        <div class="control">
            <input name="fire_service_due_date" id="fire_service_due_date" title="<?= $block->escapeHtmlAttr(__('Fire Extinguisher Service Due Date')) ?>" value="" class="input-text" type="date" />
        </div>
    </div>
    <div class="field telephone">
        <input name="fx_refill_reminder_days" id="fx_refill_reminder_days" title="<?= $block->escapeHtmlAttr(__('Check Fire Extinguisher Reminder')) ?>" value="1" class="input-text" type="checkbox" /> <label class="label inline-one" for="telephone"><span><?= $block->escapeHtml(__('Check Fire Extinguisher Reminder')) ?></span></label>
    </div>
    <div class="field telephone">
        <input name="fx_refill_reminder_days" id="fx_refill_reminder_days" title="<?= $block->escapeHtmlAttr(__('FX Expiration/Service Due Date Alert')) ?>" value="1"  class="input-text" type="checkbox" /> <label class="label inline-one" for="telephone"><span><?= $block->escapeHtml(__('FX Expiration/Service Due Date Alert')) ?></span></label>
    </div>  
</div>
<!--for AED -->
<div name="aed_no" id="aed_no" style="display:none;">
    <div class="field name ">
        <label class="label" for="name"><span><?= $block->escapeHtml(__('AED model/serial no')) ?></span></label>
        <div class="control">
            <input name="aed_serial_number" id="aed_serial_number" title="<?= $block->escapeHtmlAttr(__('AED model/serial no')) ?>" value="" class="input-text" type="text" />
        </div>
    </div>

    <div class="field subject ">
        <label class="label" for="subject"><span><?php /* @escapeNotVerified */ echo __('AED Nickname') ?></span></label>
        <div class="control">
            <input name="aed_nickname" id="aed_nickname" title="<?php /* @escapeNotVerified */ echo __('AED Nickname') ?>" value="" class="input-text" type="text" />
        </div>
    </div>

    <div class="field email ">
        <label class="label" for="email"><span><?= $block->escapeHtml(__('AED Battery Expiration Date')) ?></span></label>
        <div class="control">
            <input name="aed_battery_expiration_date" id="battery_expiration_date" title="<?= $block->escapeHtmlAttr(__('AED Battery Expiration Date')) ?>" value="" class="input-text" type="date" />
        </div>
    </div>

    <div class="field telephone">
        <label class="label" for="telephone"><span><?= $block->escapeHtml(__('AED Pad Expiration Date')) ?></span></label>
        <div class="control">
            <input name="aed_pad_expiration_date" id="pad_expiration_date" title="<?= $block->escapeHtmlAttr(__('AED Pad Expiration Date')) ?>" value="" class="input-text" type="date" />
        </div>
    </div>
    <div class="field telephone">
        <label class="label" for="telephone"><span><?= $block->escapeHtml(__('AED Service Due Date')) ?></span></label>
        <div class="control">
            <input name="aed_service_due_date" id="aed_service_due_date" title="<?= $block->escapeHtmlAttr(__('AED Service Due Date')) ?>" value="" class="input-text" type="date" />
        </div>
    </div>
    <div class="field telephone">
        <input name="aed_refill_reminder_status" id="aed_refill_reminder_status" title="<?= $block->escapeHtmlAttr(__('AED Reminder')) ?>" value="1"  class="input-text" type="checkbox" /> <label class="label inline-one" for="telephone"><span><?= $block->escapeHtml(__('AED Reminder')) ?></span></label>
    </div>
    <div class="field telephone">
        <input name="aed_refill_reminder_days" id="expiry_reminder_status" title="<?= $block->escapeHtmlAttr(__('AED Expiration/Service Due Date Alert')) ?>" value="1"  class="input-text" type="checkbox" /> <label class="label inline-one" for="telephone"><span><?= $block->escapeHtml(__('AED Expiration/Service Due Date Alert')) ?></span></label>
    </div>
</div>
<!--for Eyewash Stations  -->

<div name="eyewash_no" id="eyewash_no" style="display:none">
    <div class="field name ">
        <label class="label" for="name"><span><?= $block->escapeHtml(__('Eyewash Stations Model no')) ?></span></label>
        <div class="control">
            <input name="eyewash_model_number" id="eyewash_stations_model_number" title="<?= $block->escapeHtmlAttr(__('Eyewash Stations Model no')) ?>" value="" class="input-text" type="text" />
        </div>
    </div>

    <div class="field subject ">
        <label class="label" for="subject"><span><?php /* @escapeNotVerified */ echo __('Eyewash Stations Nickname') ?></span></label>
        <div class="control">
            <input name="eyewash_nickname" id="eyewash_stations_nickname" title="<?php /* @escapeNotVerified */ echo __('Eyewash Stations Nickname') ?>" value="" class="input-text" type="text" />
        </div>
    </div>

    <div class="field email ">
        <label class="label" for="email"><span><?= $block->escapeHtml(__('Eyewash Stations Expiration Date')) ?></span></label>
        <div class="control">
            <input name="eyewash_expiration_date" id="eyewash_stations_expiration_date" title="<?= $block->escapeHtmlAttr(__('Eyewash Stations Expiration Date')) ?>" value="" class="input-text" type="date"/>
        </div>
    </div>

    <div class="field telephone">
        <input name="eyewash_refill_reminder_status" id="check_eyewash_stations_reminder" title="<?= $block->escapeHtmlAttr(__('Check Eyewash Stations Reminder')) ?>" value="1" class="input-text" type="checkbox" /> <label class="label inline-one" for="telephone"><span><?= $block->escapeHtml(__('Check Eyewash Stations Reminder')) ?></span></label>
        <div class="control">

        </div>
    </div>

    <div class="field telephone">
        <input name="eyewash_physical_inventory_status" id="do_physical_inventory_of_eyewash_stations" title="<?= $block->escapeHtmlAttr(__('Do Physical Inventory Of Eyewash Stations')) ?>" value="1"  class="input-text" type="checkbox" /> <label class="label inline-one" for="telephone"><span><?= $block->escapeHtml(__('Do Physical Inventory Of Eyewash Stations')) ?></span></label>
    </div>
</div>

<!--for Spill Control  -->
<div name="spill_no" id="spill_no" style="display:none">
    <div class="field name ">
        <label class="label" for="name"><span><?= $block->escapeHtml(__('Spill Control Model no')) ?></span></label>
        <div class="control">
            <input name="spill_model_number" id="spill_model_number" title="<?= $block->escapeHtmlAttr(__('Spill Control Model no')) ?>" value="" class="input-text" type="text" />
        </div>
    </div>

    <div class="field subject ">
        <label class="label" for="subject"><span><?php /* @escapeNotVerified */ echo __('Spill Control Nickname') ?></span></label>
        <div class="control">
            <input name="spill_nickname" id="spill_nickname" title="<?php /* @escapeNotVerified */ echo __('Spill Control Nickname') ?>" value="" class="input-text" type="text"/>
        </div>
    </div>

    <div class="field telephone">
        <input name="spill_refill_reminder_status" id="spill_refill_reminder_status" title="<?= $block->escapeHtmlAttr(__('Check Eyewash Stations Reminder')) ?>" value="1"  class="input-text" type="checkbox" /> <label class="label inline-one" for="telephone"><span><?= $block->escapeHtml(__('Check Spill Control Reminder')) ?></span></label>
    </div>
    <div class="field telephone">
        <input name="spill_physical_inventory_status" id="physical_inventory_status" title="<?= $block->escapeHtmlAttr(__('Do Physical Inventory Of Spill Control')) ?>" value="1"  class="input-text" type="checkbox" /> <label class="label inline-one" for="telephone"><span><?= $block->escapeHtml(__('Do Physical Inventory Of Spill Control')) ?></span></label>
    </div>
</div>

<script type="text/javascript">
function showDiv(select) {
    if (select.value == 2) {
        document.getElementById('fire_extinguisher').style.display = "block";
        document.getElementById('aed_no').style.display = "none";
        document.getElementById('cabinet_no').style.display = "none";
        document.getElementById('spill_no').style.display = "none";
    } else if (select.value == 3) {
        document.getElementById('aed_no').style.display = "block";
        document.getElementById('fire_extinguisher').style.display = "none";
        document.getElementById('cabinet_no').style.display = "none";
        document.getElementById('eyewash_no').style.display = "none";
        document.getElementById('spill_no').style.display = "none";
    } else if (select.value == 4) {
        document.getElementById('eyewash_no').style.display = "block";
        document.getElementById('spill_no').style.display = "none";
        document.getElementById('cabinet_no').style.display = "none";
        document.getElementById('aed_no').style.display = "none";
        document.getElementById('fire_extinguisher').style.display = "none";
    } else if (select.value == 5) {
        document.getElementById('spill_no').style.display = "block";
        document.getElementById('eyewash_no').style.display = "none";
        document.getElementById('cabinet_no').style.display = "none";
        document.getElementById('aed_no').style.display = "none";
        document.getElementById('fire_extinguisher').style.display = "none";
    } else {
        document.getElementById('spill_no').style.display = "none";
        document.getElementById('cabinet_no').style.display = "block";
        document.getElementById('fire_extinguisher').style.display = "none";
        document.getElementById('aed_no').style.display = "none";
    }
}
</script>