<?php
$user = $block->getUserData();
$address = $block->getUserAddressData();
$userItem = $block->getUserItemData();
$companies = $block->getCompanies();
$customerPermission = $block->getCustomerPermission();
$userItemData = $userItem;
//print_r($userItemData);
//echo '<pre>';
//print_r($customerPermission);

$arrayAdd = [];
if ($address && isset($address['street']) && $address['street'] != '') {
    $fullAddress = $address['street'];
    $arrayAdd = explode(PHP_EOL, $fullAddress);
}
$companyData = $userItemData ? $block->getCompanyData($userItemData['company_id']) : [];
//print_r($companyData); 
//return; 
//$companyData = $block->getCompanyData();
//echo trim(preg_replace('/"/','',$customerPermission['permission']),'[]');
$permission = ($customerPermission && isset($customerPermission['permission']) && $customerPermission['permission'] != '') ? explode(',', trim(preg_replace('/"/', '', $customerPermission['permission']), '[]')) : [];
//print_r($permission);
?> 

<input type="hidden" name="entity_id" value="<?= $user ? $user['entity_id'] : '' ?>">
<div class="field subject required">
    <label class="label" for="firstname"><span><?php echo __('First Name') ?></span></label>
    <div class="control">
        <input name="firstname" id="firstname" title="<?php /* @escapeNotVerified */ echo __('First Name') ?>" value="<?= $user && isset($user['firstname']) ? $user['firstname'] : '' ?>" class="input-text" type="text" data-validate="{required:true}"/>
    </div>
</div>




<div class="field subject required">
    <label class="label" for="lastname"><span><?php /* @escapeNotVerified */ echo __('Last Name') ?></span></label>
    <div class="control">
        <input name="lastname" id="lastname" title="<?php /* @escapeNotVerified */ echo __('Last Name') ?>" value="<?= $user && isset($user['lastname']) ? $user['lastname'] : '' ?>" class="input-text" type="text" data-validate="{required:true}"/>
    </div>
</div>


<div class="field subject required">
    <label class="label" for="user_email"><span><?php /* @escapeNotVerified */ echo __('User Email') ?></span></label>
    <div class="control">
        <input name="user_email" id="user_email" title="<?php /* @escapeNotVerified */ echo __('User Email') ?>" value="<?= $user && isset($user['email']) ? $user['email'] : '' ?>" class="input-text" type="text" data-validate="{required:true}"/>
    </div>
</div>


<div class="field subject <?= $user ? '' : 'required' ?>">
    <label class="label" for="password"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
    <div class="control">
        <input name="password" id="password" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" value="" class="input-text" type="text" data-validate="{required:<?= $user ? 'false' : 'true' ?>}" />
    </div>
</div>

<div class="field subject <?= $user ? '' : 'required' ?>">
    <label class="label" for="con_password"><span><?php /* @escapeNotVerified */ echo __('Confirm Password') ?></span></label>
    <div class="control">
        <input name="con_password" id="con_password" title="<?php /* @escapeNotVerified */ echo __('Confirm Password') ?>" value="" class="input-text" type="text" data-validate="{required:<?= $user ? 'false' : 'true' ?>}"/>
    </div>
</div>
<div class="field subject">
    <label class="label" for="no_of_employees"><span><?php /* @escapeNotVerified */ echo __('Number of employees') ?></span></label>
    <div class="control">
        <input name="no_of_employees" id="no_of_employees" title="<?php /* @escapeNotVerified */ echo __('Number of employees') ?>" value="<?= $userItemData && isset($userItemData['number_of_employees']) ? $userItemData['number_of_employees'] : '' ?>" class="input-text" type="text" />
    </div>
</div>
<div class="field subject">
    <label class="label" for="job_title"><span><?php /* @escapeNotVerified */ echo __('Job title') ?></span></label>
    <div class="control">
        <input name="job_title" id="job_title" title="<?php /* @escapeNotVerified */ echo __('Job title') ?>" value="<?= $userItemData && isset($userItemData['job_title']) ? $userItemData['job_title'] : '' ?>"  class="input-text" type="text" />
    </div>
</div>
<div class="field subject">
    <label class="label" for="requisition_email_address"><span><?php /* @escapeNotVerified */ echo __('Requisition Email Address') ?></span></label>
    <div class="control">
        <input name="requisition_email_address" id="requisition_email_address" title="<?php /* @escapeNotVerified */ echo __('Requisition Email Address') ?>" value="<?= $userItemData && isset($userItemData['requisition_email_address']) ? $userItemData['requisition_email_address'] : '' ?>" class="input-text" type="text"/>
    </div>
</div>




<div class="field subject">
    <label class="label" for="phone"><span><?= $block->escapeHtml(__('Company Group')) ?></span></label>
    <div class="control">
        <select name="company" id="company" onChange="showPermission()" <?= $user ? 'disabled' : '' ?>>
            <option value="">Select Company</option>
            <?php foreach ($companies as $company) { ?>
                <option value="<?= $company['entity_id'] ?>" <?= $userItem && isset($userItemData['company_id']) && $userItemData['company_id'] == $company['entity_id'] ? 'selected' : '' ?>><?= $company['name'] ?></option>
            <?php } ?>
        </select>
    </div>
</div>




<div class="field subject required">
    <label class="label" for="company_name"><span><?php /* @escapeNotVerified */ echo __('Company name') ?></span></label>
    <div class="control">
        <input name="company_name" id="company_name" title="<?php /* @escapeNotVerified */ echo __('Company name') ?>" value="<?= $address && isset($address['company']) ? $address['company'] : '' ?>" class="input-text" type="text" data-validate="{required:true}"/>
    </div>
</div>

<div class="field subject required">
    <label class="label" for="add1"><span><?php /* @escapeNotVerified */ echo __('Address 1') ?></span></label>
    <div class="control">
        <input name="street" id="add1" title="<?php /* @escapeNotVerified */ echo __('Address 1') ?>" value="<?= $arrayAdd && isset($arrayAdd[0]) ? $arrayAdd[0] : '' ?>" class="input-text" type="text" data-validate="{required:true}"/>
    </div>
</div>

<div class="field subject">
    <label class="label" for="add2"><span><?php /* @escapeNotVerified */ echo __('Address 2') ?></span></label>
    <div class="control">
        <input name="add2" id="add2" title="<?php /* @escapeNotVerified */ echo __('Address 2') ?>" value="<?= $arrayAdd && isset($arrayAdd[1]) ? $arrayAdd[1] : '' ?>" class="input-text" type="text"/>
    </div>
</div> 

<div class="field subject required">
    <label class="label" for="city"><span><?php /* @escapeNotVerified */ echo __('City') ?></span></label>
    <div class="control">
        <input name="cityname" id="cityname" title="<?php /* @escapeNotVerified */ echo __('City') ?>" value="<?= $address && isset($address['city']) ? $address['city'] : '' ?>" class="input-text" type="text" data-validate="{required:true}"/>
    </div>
</div>

<div class="field telephone required">
    <label class="label" for="state"><span><?= $block->escapeHtml(__('State/Province')) ?></span></label>
    <div class="control">
        <select id="region_id" name="region_id" title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>" class="select" data-validate="{required:true}" onChange="getRegion()">
            <option value=""><?= $block->escapeHtml(__('Please select region, state or province')) ?></option>
            <?php
            foreach ($block->getStates() as $i => $username) {
                $items = $username['name'];
                ?>
                <option value="<?php echo $username['region_id']; ?>" data-rc="<?php echo $username['name']; ?>" <?php
                if ($address && isset($address['region_id']) && $address['region_id'] == $username['region_id']) {
                    echo 'selected';
                }
                ?>><?php echo $username['name']; ?></option>
                    <?php } ?>
        </select>   
        <input type="hidden" name="region" id="region" value="<?= $address && isset($address['region']) ? $address['region'] : '' ?>">
    </div>
</div>
<div class="field subject required">
    <label class="label" for="zipcode"><span><?php /* @escapeNotVerified */ echo __('Zip code') ?></span></label>
    <div class="control">
        <input name="zipcode" id="zipcode" title="<?php /* @escapeNotVerified */ echo __('Zip code') ?>" value="<?= $address && isset($address['postcode']) ? $address['postcode'] : '' ?>" class="input-text" type="text" data-validate="{required:true}"/>
    </div>
</div>
<div class="field subject required">
    <label class="label" for="telephone"><span><?php /* @escapeNotVerified */ echo __('Telephone') ?></span></label>
    <div class="control">
        <input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Telephone') ?>" value="<?= $address && isset($address['telephone']) ? $address['telephone'] : '' ?>" class="input-text" type="text" data-validate="{required:true}"/>
    </div>
</div>

<div class="field " data-role="tree-resources-container" id="showPermission" style="display:<?= $permission && count($permission) > 0 ? 'block' : 'none' ?>;">
    <label class="label"><span><?= /* @escapeNotVerified */ __('Resources') ?></span></label>
    <div class="control">
        <div class="tree x-tree jstree jstree-0 jstree-focused jstree-default">
            <ul class="jstree-no-dots">
                <li><input type="checkbox"  id="permission_type" name="permission_type" value="1" <?php
                    if ($customerPermission && $customerPermission['permission_type'] == 1) {
                        echo 'checked';
                    }
                    ?>>Assign Admin Group</li>
                <li><input type="checkbox"  id="permission_type" name="permission_type" value="2" <?php
                    if ($customerPermission && $customerPermission['permission_type'] == 2) {
                        echo 'checked';
                    }
                    ?>>Assign All Permissions</li>

            </ul>
            <ul class="jstree-no-dots">
                <li><input type="checkbox"  id="resource[]" name="resource[]" value="1" <?php
                           if (in_array('1', $permission)) {
                               echo 'checked';
                           }
                           ?>>Manage Requisitions</li>
                <li><input type="checkbox"  id="resource[]" name="resource[]" value="2" <?php
                    if (in_array('2', $permission)) {
                        echo 'checked';
                    }
                           ?>>Manage Safety Items</li>
                <li><input type="checkbox"  id="resource[]" name="resource[]" value="3" <?php
                           if (in_array('3', $permission)) {
                               echo 'checked';
                           }
                           ?>>Manage Staff</li>
                <li>
                    <input type="checkbox"  id="resource[]" name="resource[]" value="4" <?php
                    if (in_array('4', $permission)) {
                        echo 'checked';
                    }
                    ?>>Reports
                    <ul>
                        <li>&nbsp;&nbsp;Requisition Reports </li>
                        <li>&nbsp;&nbsp;Physical Inventory Check Reports</li>
                        <li>&nbsp;&nbsp;Inventory Checked Ok Report</li>   
                    </ul>
                </li>
                <li>
                    <input type="checkbox"  id="resource[]" name="resource[]" value="5" <?php
                    if (in_array('5', $permission)) {
                        echo 'checked';
                    }
                    ?>>Personalization
                    <ul>
                        <li>&nbsp;&nbsp; Manage Company Labels </li>
                        <li>&nbsp;&nbsp;Welcome Email Template</li>
                    </ul>
                </li>
                <li><input type="checkbox"  id="resource[]" name="resource[]" value="10" <?php
                    if (in_array('10', $permission)) {
                        echo 'checked';
                    }
                    ?>>Requisition Approval</li>
            </ul>

        </div>
    </div>
</div>


<div class="field telephone">
    <label class="label" for="status"><span><?= $block->escapeHtml(__('User Status')) ?></span></label>
    <div class="control">
        <select id="status" name="status" title="<?= $block->escapeHtmlAttr(__('User Status')) ?>" class="select" data-validate="{required:true}">
            <option value="1">Enable</option>
            <option value="2">Disable</option>


        </select>   
    </div>
</div>



<script>
    function getRegion(select)
    {
        var e = document.getElementById("region_id");
        var option = e.options[e.selectedIndex];
        var attrs = option.attributes;
        var datarc = option.getAttribute("data-rc");
        console.log(datarc);
        document.getElementById("region").value = datarc;
    }

    function showPermission()
    {
        var company = document.getElementById('company').value;
        if (company != '') {
            document.getElementById('showPermission').style.display = 'block';
        } else {
            document.getElementById('showPermission').style.display = 'none';
        }
    }
</script>