<form class="form contact" name="myform"
      action="<?= $block->getUrl('safetyhubapp/company/sendemailsave'); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}' enctype ='multipart/form-data'>
   
      <h2>Send Test Mail</h2>
     
    <fieldset class="fieldset">     

        <div class=" field name required">

            <label class="label" for="name"><span><?php /* @escapeNotVerified */ echo __('FullName') ?></span></label>
            <div class="control">
                <input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('FullName') ?>"  value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('name')) ?>"  class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>"  value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('email')) ?>"  class="input-text" type="email" data-validate="{required:true}"/>
            </div>
        </div>
                             
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
         <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Send')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Send')) ?></span>
            </button>
           
        </div>
        
    </div>
</form>

