<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgno
?>


<section class="admin__page-section order-view-billing-shipping">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @escapeNotVerified */ __('Cabinet') ?></span>
    </div>
   
</section>

<section class="admin__page-section order-view-billing-shipping">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @escapeNotVerified */ __('Items Order') ?></span>
		    

    </div>
   <table>
        <thead>
    	<tr>
    	    <th scope="col" class="col id"><?php echo __('Created On') ?></th>
    	    
    	</tr>
        </thead>
	
	    <tr>
		<td>yashi</td>
		
		    
	    </tr>
	
</table>
</section>


